# Generated by Django 5.2.4 on 2025-08-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FourthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
