# Generated by Django 5.2.4 on 2025-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FourthApp', '0002_company_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=1001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='emp_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
