# Generated by Django 5.2.4 on 2025-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.IntegerField()),
                ('address', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
