# Generated by Django 5.2.4 on 2025-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('stu_name', models.CharField(max_length=15)),
                ('stu_address', models.CharField(max_length=25)),
                ('stu_age', models.IntegerField()),
                ('stu_mark', models.IntegerField()),
            ],
        ),
    ]
